using System;
using System.Collections.Generic;

namespace SiyayaTravelAssist.Core.Domain
{
    public class Booking
    {
        public Booking()
        {
            BookingTrips = new HashSet<BookingTrip>();
        }
        
        public int Id { get; set; }
        public string BookingStatus { get; set; } //Booking Status(Completed or whatever)
        //public string ClientReference { get; set; } 
        public DateTime DateCreated { get; set; }
      
       

        public string BookingReference { get; set; } //For Enquirers From Client , auto-generated by system
        public string BookingOrder { get; set; } // We receive this one from them, it is their reference given to us
        public double PaymentBalance { get; set; } //Amount
        public string PaymentType { get; set; } // Type Of Payment
        public string PaymentStatus { get; set; } //Payment Status(Payed, Deposit  or whatever)
        public string AdditionalInformation { get; set; }
        public int NumberOfPassengers { get; set; }



        //One Client- Many Bookings (Booking is like H)
        public virtual Client Client { get; set; }
        public int ClientId { get; set; }

      

        //Zero Or One Quote - One Booking
        public Quote Quote { get; set; }


        //One Booking - Many BookingTrips (Booking is like C)
        public ICollection<BookingTrip> BookingTrips { get; set; }


        //One BookingType - Many Bookings (Booking is like H)
        public virtual BookingType BookingType { get; set; }
        public int BookingTypeId { get; set; }
      

     
    }
}