using System;
using System.Collections.Generic;

namespace SiyayaTravelAssist.Core.Domain
{
    public class Booking
    {
        
        public int Id { get; set; }
        public string Status { get; set; }
        public string ClientReference { get; set; } // Id or Registration Number
        public DateTime DateCreated { get; set; }
        public string BookingReference { get; set; } //For Enquirers From Client , auto-generated by system
        public string BookingOrder { get; set; } // We receive this one from them, it is their reference given to us


        //public Trip TripId { get; set; } //One Booking - One Trip
        public Client ClientId { get; set; }  //One To One
        public Invoice InvoiceId { get; set; } // One Invoice to One Booking


     
    }
}